mod commands;
pub mod options;
mod query;
pub mod types;

pub use commands::{
    display_message, get_all_global_options, get_pane_option_value, run_tmux, select_pane,
    set_pane_option, unset_pane_option,
};
pub use options::{
    PANE_AGENT, PANE_ATTENTION, PANE_BG_CMD, PANE_CWD, PANE_LAST_SEEN_AT, PANE_NAME,
    PANE_PERMISSION_MODE, PANE_PROMPT, PANE_PROMPT_SOURCE, PANE_ROLE, PANE_SESSION_ID,
    PANE_STARTED_AT, PANE_STATUS, PANE_SUBAGENTS, PANE_WAIT_REASON, PANE_WORKTREE_BRANCH,
    PANE_WORKTREE_NAME, SIDEBAR_COLOR_ACCENT, SIDEBAR_COLOR_ACTIVITY_TIMESTAMP,
    SIDEBAR_COLOR_AGENT_CLAUDE, SIDEBAR_COLOR_AGENT_CODEX, SIDEBAR_COLOR_AGENT_OPENCODE,
    SIDEBAR_COLOR_ALL, SIDEBAR_COLOR_BADGE_AUTO, SIDEBAR_COLOR_BADGE_DANGER,
    SIDEBAR_COLOR_BADGE_PLAN, SIDEBAR_COLOR_BORDER, SIDEBAR_COLOR_BRANCH, SIDEBAR_COLOR_ERROR,
    SIDEBAR_COLOR_FILTER_INACTIVE, SIDEBAR_COLOR_IDLE, SIDEBAR_COLOR_RESPONSE_ARROW,
    SIDEBAR_COLOR_RUNNING, SIDEBAR_COLOR_SECTION_TITLE, SIDEBAR_COLOR_SELECTION,
    SIDEBAR_COLOR_SESSION, SIDEBAR_COLOR_TEXT_ACTIVE, SIDEBAR_COLOR_TEXT_INACTIVE,
    SIDEBAR_COLOR_TEXT_MUTED, SIDEBAR_COLOR_WAIT_REASON, SIDEBAR_COLOR_WAITING, SIDEBAR_ICON_ALL,
    SIDEBAR_ICON_BACKGROUND, SIDEBAR_ICON_ERROR, SIDEBAR_ICON_IDLE, SIDEBAR_ICON_RUNNING,
    SIDEBAR_ICON_UNKNOWN, SIDEBAR_ICON_WAITING, get_option,
};
pub use query::query_sessions;
pub use types::{
    AgentType, PaneInfo, PaneStatus, PermissionMode, SessionInfo, WindowInfo, WorktreeMetadata,
};
